class_name RandoManager extends Control



const YAML_FILE_PATH := "user://Data/Players/%s.yaml"

const YAML_FILE_LAYOUT := """name: %s
description: YAML generated by MIO's interactive map
game: %s
%s:
  progression_balancing: normal
  accessibility: full
  local_items: []
  non_local_items: []
  start_inventory: {}
  start_hints: []
  start_location_hints: []
  exclude_locations: []
  priority_locations: []
  start_inventory_from_pool: {}%s
"""

@onready var option_nodes: Dictionary[String, Control] = {
	"logic_level": $SplitContainer/Options/Control/GridContainer/Logic,
	"randomize_slash": $SplitContainer/Options/Control/GridContainer/Slash,
	"goal": $SplitContainer/Options/Control/GridContainer/Ending,
	"death_link": $SplitContainer/Options/Control/GridContainer/DeathLink,
}


func _ready() -> void:
	get_parent().get_node("Saves").validate_folders(YAML_FILE_PATH.trim_suffix("%s.yaml"))
	get_viewport().size_changed.connect(update_alignment)


func update_alignment() -> void:
	var view_size := get_viewport_rect().size
	$SplitContainer.vertical = view_size.y > view_size.x


func construct_yaml() -> String:
	return YAML_FILE_LAYOUT % [
		$SplitContainer/Options/Control/GridContainer/Name.text,
		"Manual_MIO_Samwell", "Manual_MIO_Samwell",
		join_dictionary(get_current_options(), ": ", "\n  ", "\n  ")
	]


static func join_dictionary(dict: Dictionary[String, String], key_to_value: String, value_to_key: String, starting := "") -> String:
	if dict.is_empty():
		return ""
	
	var result := starting
	for i in dict:
		result += i
		result += key_to_value
		result += dict[i]
		result += value_to_key
	result.trim_suffix(value_to_key)
	return result


func get_current_options() -> Dictionary[String, String]:
	var result: Dictionary[String, String]
	for i in option_nodes:
		match option_nodes[i].get_class():
			"OptionButton":
				result[i] = option_nodes[i].get_item_text(option_nodes[i].selected).to_lower()
			"CheckBox":
				result[i] = str(option_nodes[i].button_pressed)
			"CheckButton":
				result[i] = str(option_nodes[i].button_pressed)
	return result


func save_yaml(contents_string: String, file_name: String) -> void:
	var file := FileAccess.open(YAML_FILE_PATH % file_name, FileAccess.WRITE)
	file.store_string(contents_string)
	file.close()


func load_yaml(file_name: String) -> Dictionary[String, String]:
	var result: Dictionary[String, String]
	if not FileAccess.file_exists(YAML_FILE_PATH % file_name):
		return result
	var file := FileAccess.open(YAML_FILE_PATH % file_name, FileAccess.READ)
	var text := file.get_as_text()
	if text.is_empty():
		return result
	text = text.get_slice("Manual_MIO_Samwell:", 1)
	var split: Array[String]
	split.assign(Array(text.split("\n  ")))
	for i in split:
		var key_val_split: Array[String]
		key_val_split.assign(Array(i.split(": ")))
		result[key_val_split[0]] = key_val_split[1]
	return result


func read_yaml_data(data: Dictionary[String, String]) -> Dictionary[String, Variant]:
	var result: Dictionary[String, Variant]
	for i in option_nodes:
		match option_nodes[i].get_class():
			"OptionButton":
				result[i] = Globals.capitalize_first(data[i])
			"CheckBox":
				result[i] = data[i] == "true"
			"CheckButton":
				result[i] = data[i] == "true"
	return result


func generate(from_yaml := "", state := Main.player_state) -> void:
	var data: Dictionary[String, Variant]
	if from_yaml.is_empty():
		data = read_yaml_data(get_current_options())
	else:
		data = read_yaml_data(load_yaml(from_yaml))
	
	var location_assignments: Dictionary[String, String]
	var available_prog_items: Array[String]
	var available_useful_items: Array[String]
	var available_filler_items: Array[String]
	var all_locs: Array[String]
	var available_locs: Array[String]
	var locs_left: Array[String]
	var all_rooms: Array[String]
	var available_rooms: Array[String]
	var rooms_left: Array[String]
	
	for item: Item in %ItemPool.get_children():
		var list_to_add: Array[String]
		if item.type == Item.ItemTypes.EVENT:
			continue
		match item.classification:
			Item.ItemClassifications.PROGRESSION:
				list_to_add = available_prog_items
			Item.ItemClassifications.USEFUL:
				list_to_add = available_useful_items
			_:
				list_to_add = available_filler_items
		for i in range(item.max_amount):
			list_to_add.append(item.item_name)
	for loc: LocationPanel in $"../LocationRequirements/VBoxContainer".get_children():
		all_locs.append(loc.serialize())
	for room: RoomPanel in $"../Map/SubViewportContainer/SubViewport/Node2D/Panels".get_children():
		all_rooms.append(room.room_id)
	
	match data.logic_level:
		"No Logic":
			available_locs.assign(all_locs)
			while not available_locs.is_empty():
				var current_loc: String = available_locs.pick_random()
				var current_item: String
				for i in [available_prog_items, available_useful_items, available_filler_items]:
					if not i.is_empty():
						current_item = i.pick_random()
						i.erase(current_item)
						break
				if current_item == "":
					current_item = "Crystallised Nacre"
				location_assignments[current_loc] = current_item
				available_locs.erase(current_loc)
		"Intended Logic":
			var old_state := Main.player_state
			Main.player_state = Main.PlayerState.new()
			if not data.randomize_slash:
				Main.player_state.prog_items.assign(["Slash"])
			available_rooms.assign(Globals.main.get_reachable())
			available_locs.assign(Globals.main.get_reachable_locations(available_rooms).map(func(e): return e.serialize()))
			if not data.randomize_slash:
				available_locs.erase("ST_security_fall_P1: Starting Item (Slash)")
			rooms_left.assign(all_rooms.filter(func(e): return not e in available_rooms))
			locs_left.assign(all_locs)#.filter(func(e): return not e in available_locs))
			
			while not available_locs.is_empty():
				await get_tree().process_frame
				print(available_locs)
				calculate_next_sphere(location_assignments, available_rooms, rooms_left, locs_left, 
					available_prog_items, available_useful_items, available_filler_items)
			
			Main.player_state = old_state
			print(available_rooms)
			print(available_locs)
			pass #available_locs = 
	
	state.rando_assignments = location_assignments


func calculate_next_sphere(loc_assignments: Dictionary[String, String], available_rooms: Array[String], 
		rooms_left: Array[String], locs_left: Array[String], 
		prog_items_left: Array[String], useful_items_left: Array[String], filler_items_left: Array[String]) -> void:
	
	var new_available_rooms: Array[String]
	for transition: TransitionPanel in $"../TransitionRequirements/VBoxContainer".get_children():
		if transition.from in available_rooms and transition.to in rooms_left:
			if transition.intended_logic.call():
				new_available_rooms.append(transition.to)
				rooms_left.erase(transition.to)
	available_rooms += new_available_rooms
	var new_available_locs: Array[String]
	for location: LocationPanel in $"../LocationRequirements/VBoxContainer".get_children():
		var serialized := location.serialize()
		if serialized in locs_left:
			if location.intended_logic.call():
				new_available_locs.append(serialized)
				locs_left.erase(serialized)
	
	var possible_assignments := get_new_assignments(new_available_locs, prog_items_left + useful_items_left + filler_items_left)
	var new_locs := get_theoretical_new_locs(possible_assignments.values(), available_rooms, rooms_left, locs_left)
	while new_locs.is_empty():
		print(new_locs)
		possible_assignments = get_new_assignments(new_available_locs, prog_items_left + useful_items_left + filler_items_left)
		new_locs = get_theoretical_new_locs(possible_assignments.values(), available_rooms, rooms_left, locs_left)
	
	for i in possible_assignments:
		loc_assignments[i] = possible_assignments[i]


func get_new_assignments(available_locs: Array[String], items_left: Array[String]) -> Dictionary[String, String]:
	var result: Dictionary[String, String]
	for i in available_locs:
		result[i] = items_left.pick_random()
		items_left.erase(result[i])
	return result


func get_theoretical_new_locs(itempool: Array[String], available_rooms: Array[String], rooms_left: Array[String], locs_left: Array[String]) -> Array[String]:
	var old_state := Main.player_state
	Main.player_state = Main.PlayerState.new()
	Main.player_state.prog_items.assign(itempool)
	
	# copied code but idc at this point it just has to work
	var new_available_rooms: Array[String]
	for transition: TransitionPanel in $"../TransitionRequirements/VBoxContainer".get_children():
		if transition.from in available_rooms and transition.to in rooms_left:
			if transition.intended_logic.call():
				new_available_rooms.append(transition.to)
				rooms_left.erase(transition.to)
	for i in new_available_rooms:
		rooms_left.append(i)
	available_rooms += new_available_rooms
	var new_available_locs: Array[String]
	for location: LocationPanel in $"../LocationRequirements/VBoxContainer".get_children():
		var serialized := location.serialize()
		if serialized in locs_left:
			print(serialized)
			if location.intended_logic.call():
				new_available_locs.append(serialized)
				locs_left.erase(serialized)
	for i in new_available_locs:
		locs_left.append(i)
	
	Main.player_state = old_state
	return new_available_locs


func start_rando(from_yaml := "") -> void:
	generate(from_yaml)
	#for i in Main.player_state.rando_assignments:
		#print(i + ": " + Main.player_state.rando_assignments[i])
	Globals.is_solo_rando = true


func _on_download_button_pressed() -> void:
	var text: String = $SplitContainer/Options/Control/GridContainer/Name.text
	save_yaml(construct_yaml(), text)
	
	if OS.has_feature("web"):
		var json := FileAccess.get_file_as_string(YAML_FILE_PATH % text)
		JavaScriptBridge.download_buffer(json.to_utf8_buffer(), text + ".yaml")


func _on_start_pressed() -> void:
	start_rando()
