class_name RandoManager extends Control


const YAML_FILE_PATH := "user://Data/Players/%s.yaml"

const YAML_FILE_LAYOUT := """name: %s
description: YAML generated by MIO's interactive map
game: %s
%s:
  progression_balancing: normal
  accessibility: full
  local_items: []
  non_local_items: []
  start_inventory: {}
  start_hints: []
  start_location_hints: []
  exclude_locations: []
  priority_locations: []
  start_inventory_from_pool: {}%s
"""

@onready var option_nodes: Dictionary[String, Control] = {
	"logic_level": $SplitContainer/Options/Control/GridContainer/Logic,
	"randomize_slash": $SplitContainer/Options/Control/GridContainer/Slash,
	"goal": $SplitContainer/Options/Control/GridContainer/Ending,
	"death_link": $SplitContainer/Options/Control/GridContainer/DeathLink,
}


func _ready() -> void:
	get_parent().get_node("Saves").validate_folders(YAML_FILE_PATH.trim_suffix("%s.yaml"))
	get_viewport().size_changed.connect(update_alignment)


func update_alignment() -> void:
	var view_size := get_viewport_rect().size
	$SplitContainer.vertical = view_size.y > view_size.x


func construct_yaml() -> String:
	return YAML_FILE_LAYOUT % [
		$SplitContainer/Options/Control/GridContainer/Name.text,
		"Manual_MIO_Samwell", "Manual_MIO_Samwell",
		join_dictionary(get_current_options(), ": ", "\n  ", "\n  ")
	]


static func join_dictionary(dict: Dictionary[String, String], key_to_value: String, value_to_key: String, starting := "") -> String:
	if dict.is_empty():
		return ""
	
	var result := starting
	for i in dict:
		result += i
		result += key_to_value
		result += dict[i]
		result += value_to_key
	result.trim_suffix(value_to_key)
	return result


func get_current_options() -> Dictionary[String, String]:
	var result: Dictionary[String, String]
	for i in option_nodes:
		match option_nodes[i].get_class():
			"OptionButton":
				result[i] = option_nodes[i].get_item_text(option_nodes[i].selected).to_lower()
			"CheckBox":
				result[i] = str(option_nodes[i].button_pressed)
			"CheckButton":
				result[i] = str(option_nodes[i].button_pressed)
	return result


func save_yaml(contents_string: String, file_name: String) -> void:
	var file := FileAccess.open(YAML_FILE_PATH % file_name, FileAccess.WRITE)
	file.store_string(contents_string)
	file.close()


func _on_download_button_pressed() -> void:
	var text: String = $SplitContainer/Options/Control/GridContainer/Name.text
	save_yaml(construct_yaml(), text)
	
	if OS.has_feature("web"):
		var json := FileAccess.get_file_as_string(YAML_FILE_PATH % text)
		JavaScriptBridge.download_buffer(json.to_utf8_buffer(), text + ".yaml")
